name: C/C++ CI
on: [ push ]
jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      # TODO use https://github.com/marketplace/actions/cache-apt-packages
      - name: Set up devtools
        run: |
          sudo apt install -y g++ cmake ninja-build

      # https://github.com/marketplace/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt;
          fi

      # see also https://github.com/marketplace/actions/cmake-action
      - name: Configure the project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake -G Ninja -S . -B build
      - name: Build the project
        run: |
          cmake --build build -j "$(nproc)" --verbose
      - name: Test the project
        run: |
          cmake --build build --target test
